// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbdhpZC2nq8OHt0jlSmD_ZpGreKWNMfbg',
    appId: '1:981647102854:web:b454db355bb7d0f8a7d207',
    messagingSenderId: '981647102854',
    projectId: 'sports-app-e8612',
    authDomain: 'sports-app-e8612.firebaseapp.com',
    storageBucket: 'sports-app-e8612.firebasestorage.app',
    measurementId: 'G-PZGKB88LYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOvk-GmgR4skCkKU7EWNPQkq4kgPdZzbk',
    appId: '1:981647102854:android:6fee401ea6ee8d69a7d207',
    messagingSenderId: '981647102854',
    projectId: 'sports-app-e8612',
    storageBucket: 'sports-app-e8612.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAye5ac8zPXvbQYi4iXMdKaj_O2mLGq_-E',
    appId: '1:981647102854:ios:33a1e2284be8093fa7d207',
    messagingSenderId: '981647102854',
    projectId: 'sports-app-e8612',
    storageBucket: 'sports-app-e8612.firebasestorage.app',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAye5ac8zPXvbQYi4iXMdKaj_O2mLGq_-E',
    appId: '1:981647102854:ios:33a1e2284be8093fa7d207',
    messagingSenderId: '981647102854',
    projectId: 'sports-app-e8612',
    storageBucket: 'sports-app-e8612.firebasestorage.app',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbdhpZC2nq8OHt0jlSmD_ZpGreKWNMfbg',
    appId: '1:981647102854:web:5b6bee53c07031efa7d207',
    messagingSenderId: '981647102854',
    projectId: 'sports-app-e8612',
    authDomain: 'sports-app-e8612.firebaseapp.com',
    storageBucket: 'sports-app-e8612.firebasestorage.app',
    measurementId: 'G-V53KVJ53J4',
  );
}
